engines:
  duplication:
    enabled: true
    checks:
      Similar code:
        enabled: false
    config:
      languages:
      - javascript
  fixme:
    enabled: true
  eslint:
    enabled: true
ratings:
  paths:
  - "server/*.js"
  - "server/**/*.js"
exclude_paths:
- client/
- server/src/models/
- test/
- server/test/
- template/
