sudo: required

language: node_js

node_js: 
   - "stable"

before_script: 
   - npm install
   - psql -c 'create database travis;' -U postgres   
   - "./node_modules/.bin/babel-node ./server/setUpDb"
   
script: 
   -  "./node_modules/.bin/mocha --compilers js:babel-core/register ./test/**/*.js --exit"

after_success: npm run coverage
