sudo: required

language: node_js

node_js: 
   - "stable"

before_script: 
   - npm install
   - psql -c 'create database travis;' -U postgres   
   - "export NODE_ENV=test && ./node_modules/.bin/babel-node ./server/setUpDatabase"
   
script: 
   -  "npm run test:server"

after_success: npm run coverage

after_failure: npm run coverage
