sudo: required

language: node_js

node_js: 
   - "stable"

before_script: 
   - npm install
   - psql -c 'create database travis;' -U postgres   
   - "./node_modules/.bin/babel-node ./server/setUpDatabase"
   
script: 
   -  "./node_modules/.bin/mocha --compilers js:babel-core/register --require babel-polyfill ./server/test/testPath.js --exit"

after_success: npm run coverage

after_failure: npm run coverage
