// Asynchronous Processes
export const ADDING_USER = 'ADDING_USER';
export const LOGGING_USER = 'LOGGING_USER';
export const ADDING_ADMIN = 'ADDING_ADMIN';
export const CHANGING_PASSWORD = 'CHANGING_PASSWORD';
export const DELETING_ACCOUNT = 'DELETING_ACCOUNT';

export const FETCHING_EVENTS = 'FETCHING_EVENTS';
export const ADDING_EVENT = 'ADDING_EVENT';
export const UPDATING_EVENT = 'UPDATING_EVENT';
export const DELETING_EVENT = 'DELETING_EVENT';

export const FETCHING_CENTERS = 'FETCHING_CENTERS';
export const ADDING_CENTER = 'ADDING_CENTER';
export const UPDATING_CENTER = 'UPDATING_CENTER';

export const FETCHING_TRANSACTIONS = 'FETCHING_TRANSACTIONS';
export const DELETING_TRANSACTION = 'DELETING_TRANSACTION';
