// User action types
export const ADDING_USER = 'ADDING_USER';
export const ADDING_USER_RESOLVED = 'ADDING_USER_RESOLVED';
export const ADDING_USER_REJECTED = 'ADDING_USER_REJECTED';

export const LOGGING_USER = 'LOGGING_USER';
export const LOGGING_USER_RESOLVED = 'LOGGING_USER_RESOLVED';
export const LOGGING_USER_REJECTED = 'LOGGING_USER_REJECTED';

export const ADDING_ADMIN = 'ADDING_ADMIN';
export const ADDING_ADMIN_RESOLVED = 'ADDING_ADMIN_RESOLVED';
export const ADDING_ADMIN_REJECTED = 'ADDING_ADMIN_REJECTED';

export const CHANGING_PASSWORD = 'CHANGING_PASSWORD';
export const CHANGING_PASSWORD_RESOLVED = 'CHANGING_PASSWORD_RESOLVED';
export const CHANGING_PASSWORD_REJECTRED = 'CHANGING_PASSWORD_REJECTRED';

export const CLEAR_USER_STATUS = 'CLEAR_USER_STATUS';

export const CLEAR_USER = 'CLEAR_USER';

// Center action types
export const FETCHING_CENTERS = 'FETCHING_CENTERS';
export const FETCHING_CENTERS_RESOLVED = 'FETCHING_CENTERS_RESOLVED';
export const FETCHING_CENTERS_REJECTED = 'FETCHING_CENTERS_REJECTED';

export const ADDING_CENTER = 'ADDING_CENTER';
export const ADDING_CENTER_RESOLVED = 'ADDING_CENTER_RESOLVED';
export const ADDING_CENTER_REJECTED = 'ADDING_CENTER_REJECTED';

export const UPDATING_CENTER = 'UPDATING_CENTER';
export const UPDATING_CENTER_RESOLVED = 'UPDATING_CENTER_RESOLVED';
export const UPDATING_CENTER_REJECTED = 'UPDATING_CENTER_REJECTED';

export const BOOK = 'BOOK';
export const SHOW_CENTER_MODAL = 'SHOW_CENTER_MODAL';
export const CLEAR_CENTER_STATUS = 'CLEAR_CENTER_STATUS';

// Event action types
export const FETCHING_EVENTS = 'FETCHING_EVENTS';
export const FETCHING_EVENTS_RESOLVED = 'FETCHING_EVENTS_RESOLVED';
export const FETCHING_EVENTS_REJECTED = 'FETCHING_EVENTS_REJECTED';

export const ADDING_EVENT = 'ADDING_EVENTS';
export const ADDING_EVENT_RESOLVED = 'ADDING_EVENTS_RESOLVED';
export const ADDING_EVENT_REJECTED = 'ADDING_EVENTS_REJECTED';

export const UPDATING_EVENT = 'UPDATING_EVENT';
export const UPDATING_EVENT_RESOLVED = 'UPDATING_EVENT_RESOLVED';
export const UPDATING_EVENT_REJECTED = 'UPDATING_EVENT_REJECTED';

export const DELETING_EVENT = 'DELETING_EVENT';
export const DELETING_EVENT_RESOLVED = 'DELETING_EVENT_RESOLVED';
export const DELETING_EVENT_REJECTED = 'DELETING_EVENT_REJECTED';

export const CLEAR_EVENT_STATUS = 'CLEAR_EVENT_STATUS';

// Transaction action types
export const FETCHING_TRANSACTIONS = 'FETCHING_TRANSACTIONS';
export const FETCHING_TRANSACTIONS_RESOLVED = 'FETCHING_TRANSACTIONS_RESOLVED';
export const FETCHING_TRANSACTIONS_REJECTED = 'FETCHING_TRANSACTIONS_REJECTED';

export const DELETING_TRANSACTION = 'DELETING_TRANSACTION';
export const DELETING_TRANSACTION_RESOLVED = 'DELETING_TRANSACTION_RESOLVED';
export const DELETING_TRANSACTION_REJECTED = 'DELETING_TRANSACTION_REJECTED';

export const CLEAR_TRANSACTION_STATUS = 'CLEAR_TRANSACTION_STATUS';

// Action types common to two or more actions.
export const INITIALIZE_EDIT = 'INITIALIZE_EDIT';
